mainSections:
  - post
rssFullContent: true
favicon: img/favicon.png
SortBy: default
footer:
  since: 2020
  customText: "All rights reserved."
dateFormat:
  published: :date_full
  lastUpdated: :date_full
sidebar:
  # emoji: 🍥
  # subtitle: 'A personal blog about computer science and life.'
  subtitle: 'Sajjad Ziaenezhad Shirazi'
  avatar: img/derock.jpg
article:
  headingAnchor: true
  math: false
  readingTime: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0
widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc
opengraph:
  twitter:
    site: ""
    card: summary_large_image
colorScheme:
  toggle: true
  default: auto
comments:
  enabled: true
  provider: disqus
