image: alpine:3.20

variables:
  HUGO_VERSION: "0.139.3"
  HUGO_ENV: production
  PUBLIC_DIR: "public"

  # ArvanCloud settings (set these in GitLab CI variables)
  ARVAN_ENDPOINT: s3.ir-thr-at1.arvanstorage.ir
  ARVAN_BUCKET: ziaenezhad
  # AWS_ACCESS_KEY_ID
  # AWS_SECRET_ACCESS_KEY

  AWS_EC2_METADATA_DISABLED: "true"

cache:
  key: hugo-cache
  paths:
    - resources/

before_script:
  - apk add --no-cache curl bash git aws-cli
  - curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
  - tar -xzf hugo.tar.gz
  - mv hugo /usr/local/bin/hugo
  - hugo version

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - hugo --minify --gc
  artifacts:
    paths:
      - ${PUBLIC_DIR}

deploy:
  stage: deploy
  needs: ["build"]
  only:
    - main
    - master
  script:
    - aws configure set default.s3.addressing_style path
    - >
      aws s3 sync ${PUBLIC_DIR}/ s3://${ARVAN_BUCKET}/
      --endpoint-url ${ARVAN_ENDPOINT}
      --delete
    #--no-progress
